org: timour275
app: authtutorial
service: authentication-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  httpApi:
    cors: true
  timeout: 30
  memorySize: 500
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  createAuction:
    handler: src/createAuction.handler
    events:
      - http:
          path: /createAuction
          method: post
  getAuctions:
    handler: src/getAuctions.handler
    events:
      - http:
          path: /getAuctions
          method: get
  getAuction:
    handler: src/getAuctionById.handler
    events:
      - http:
          path: /auction/{id}
          method: get
  placeBid:
    handler: src/placeBid.handler
    events:
      - http:
          path: /auction/{id}/bid
          method: PATCH



resources:
  Resources:
    AuctionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline
  - serverless-bundle
 

custom:
  serverless-offline:
    httpPort: 3003
    bundle:
    linting: false

#functions:
 # api:
  #  handler: index.handler
   # events:
     # - httpApi:
      #    path: /
       #   method: get
